version: '3'
services:

  # The Application
  laravel:
    build:
      context: ./
      dockerfile: laravel.dockerfile
    container_name: ${APP_NAME}-laravel
    volumes:
      - ./laravel:/var/www
      - ./.env:/var/www/.env
    env_file:
      - .env
    networks:
      - frontend
      - backend_aula
  # The Web Server
  web:
    image: nginx
    container_name: ${APP_NAME}-web
    volumes:
      - ./web.conf:/etc/nginx/conf.d/default.conf
      - ./laravel:/var/www/
    ports:
      - 8888:80
    networks:
      - frontend

  # The Database
  db_aula:
    image: postgres:9.5-alpine
    container_name: ${APP_NAME}-db
    volumes:
        - "dbaula:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "5431:5432"
    networks:
      - backend_aula

volumes:
  dbaula:

networks:
    frontend:
    backend_aula: